const productData = [
  {
    id: 1,
    title: "Nook Lounge Stand",
    description:
      "The Nook lounge stand is the best for you. You can never go wrong with any of our products. All have been created by our amazing designers to bring you the best you can get.",
    details: {
      dimension: "L-530mm x W-510mm x H-700mm, SH-450mm",
      base: "With legs",
      baseMaterial: "Wood, Brass",
      brand: "Mezzo",
      color: "White, Peach, Walnut",
      country: "Portugal",
      feature: "Medium back",
      style: "Mid century",
    },
    price: 230,
    discountPercentage: 30,
    rating: 3.69,
    stock: 94,
    category: "Stands",
    image: "/images/products/product-01.webp",
  },
  {
    id: 2,
    title: "Capitol Complex Stand",
    description:
      "The Capitol Complex stand is the best for you. You can never go wrong with any of our products. All have been created by our amazing designers to bring you the best you can get.",
    details: {
      dimension: "L-530mm x W-510mm x H-700mm, SH-450mm",
      base: "With legs",
      baseMaterial: "Wood, Brass",
      brand: "Mezzo",
      color: "White, Peach, Walnut",
      country: "Portugal",
      feature: "Medium back",
      style: "Mid century",
    },
    price: 200,
    discountPercentage: 20,
    rating: 2.69,
    stock: 14,
    category: "Stands",
    image: "/images/products/product-02.webp",
  },
  {
    id: 3,
    title: "Ashby Dining Sofa",
    description:
      "The Ashby dining sofa is the best for you. You can never go wrong with any of our products. All have been created by our amazing designers to bring you the best you can get.",
    details: {
      dimension: "L-530mm x W-510mm x H-700mm, SH-450mm",
      base: "With legs",
      baseMaterial: "Wood, Brass",
      brand: "Verun",
      color: "White, Peach, Walnut",
      country: "Portugal",
      feature: "Medium back",
      style: "Mid century",
    },
    price: 230,
    discountPercentage: 20,
    rating: 5.0,
    stock: 14,
    category: "Sofas",
    image: "/images/products/product-03.webp",
  },
  {
    id: 4,
    title: "Serbium one-sit sofa",
    description:
      "The serbium one-sit sofa is the best for you. You can never go wrong with any of our products. All have been created by our amazing designers to bring you the best you can get.",
    details: {
      dimension: "L-530mm x W-510mm x H-700mm, SH-450mm",
      base: "With legs",
      baseMaterial: "Wood, Brass",
      brand: "Mezzo",
      color: "White, Peach, Walnut",
      country: "Portugal",
      feature: "Medium back",
      style: "Mid century",
    },
    price: 300,
    discountPercentage: 10,
    rating: 4.69,
    stock: 24,
    category: "Sofas",
    image: "/images/products/product-01.webp",
  },
];

export default productData;
